$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
type: command
name: train
display_name: Train RandomForest
inputs:
  train_data:
    type: uri_folder
  test_data:
    type: uri_folder
  max_depth:
    type: integer
  criterion:
    type: string
outputs:
  model_output:
    type: uri_folder
code: .
command: >-
  python train.py
  --train_data ${{inputs.train_data}}
  --test_data ${{inputs.test_data}}
  --model_output ${{outputs.model_output}}
  --max_depth ${{inputs.max_depth}}
  --criterion ${{inputs.criterion}}
  --n_estimators 100
environment: azureml:used-car-train-env@latest
