channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - azureml-mlflow==1.13.0  # Stable for tracking/metadata
      - azure-ai-ml==1.0.0
      - pyarrow==10.0.0
      - scikit-learn==1.2.2  # Bumped: Fixes serialization warnings
      - pandas==1.2.1
      - joblib==1.0.0
      - matplotlib==3.3.3
      - mlflow==2.9.2 # Explicit: Better Azure MLflow integration
      - cloudpickle==2.2.1  # Matches new MLflow/sklearn
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
