channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip:
      - azureml-mlflow==1.13.0
      - azure-ai-ml==1.0.0
      - pyarrow==10.0.0
      - scikit-learn==1.2.2
      - pandas==1.2.1
      - joblib>=1.1.1
      - matplotlib==3.3.3
      - mlflow==2.9.2
      - cloudpickle==2.2.1
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-client
      - git+https://github.com/microsoft/AzureML-Observability#subdirectory=aml-obs-collector
 
 
 
 
 
 
 
 
 
 
 
 
 
